# Pilz Industrial Motion Planner - Cartesian limits
# For linear and circular motions in Cartesian space

cartesian_limits:
  max_trans_vel: 0.5      # m/s - Maximum translational velocity
  max_trans_acc: 2.0      # m/s^2 - Maximum translational acceleration
  max_trans_dec: -2.0     # m/s^2 - Maximum translational deceleration
  max_rot_vel: 1.57       # rad/s - Maximum rotational velocity (~90 deg/s)
  max_rot_acc: 3.14       # rad/s^2 - Maximum rotational acceleration
  max_rot_dec: -3.14      # rad/s^2 - Maximum rotational deceleration

